version: "3.8"

services:
  server:
    build: ./server/
    ports:
      - "8000:8000"
    networks:
      - c2

  client:
    build: ./client/
    ports:
      - "8321:8321"
    networks:
      - c2

networks:
  c2:
    driver: bridge

